project_name: attiny-controller

release:
  github:
    owner: TheCacophonyProject
    name: attiny-controller
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: attiny-controller

nfpm:
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cameron Ryan-Pears <cameron@cacophony.org.nz>
  description: Controls the ATtiny on the Pi Hat
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/attiny-controller.service": "/etc/systemd/system/attiny-controller.service"
    "_release/org.cacophony.Attiny.conf": "/etc/dbus-1/system.d/org.cacophony.Attiny.conf"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
